on: [push]
name: Backward compatibility check

jobs:
  bc_check:
    name: Backward compatibility check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: fetch tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - name: Set ownership
        run: |
          # this is to fix GIT not liking owner of the checkout dir
          chown -R $(id -u):$(id -g) $PWD

      - name: Roave BC Check
        uses: docker://nyholm/roave-bc-check-ga
